---
- name: TEST
  hosts: all
  tasks:
  - name: Install Aapache2
    apt: name=apache2 state=latest
    when: ansible_os_family =="Debian"

  - name: Install Nginx
    yum: name=httpd state=absent
    when: ansible_os_family =="Redhat"

  - name: Start Apache2 and enablyad
    service: name=httpd state=started enabled=yes
    when: ansible_os_family =="Redhat"

  - name: Start Apache2 and enablyad
    service: name=apache2 state=started enabled=yes
    when: ansible_os_family =="Debian"
